services:
  web:
    build: .
    environment:
      PHX_SERVER: 1
      DATABASE_URL: ecto://postgres:postgres@db/aht20_tracker
      SECRET_KEY_BASE: 4A4AhJyMJ0TBNEG2d/j6bABBHfeqP3bl5CbSd/th8bs/M5Asm2CqgiSCi5BQbJ0S
    depends_on:
      - db
    ports:
      - 4000:4000
  db:
    image: timescale/timescaledb:2.19.3-pg17-oss
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aht20_tracker
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
  grafana:
    image: grafana/grafana:12.0.0
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  dbdata:
  grafana-data:
